kind: Pod
apiVersion: v1
metadata:
  name: resource
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
       # soft limit
       requests:
        memory: "20Mi"  
        cpu: "50m"
       # hard limit
       limits: 
        memory: "58Mi"
        cpu: "100m"