kind: Service
apiVersion: v1
metadata:
 name: nginx # Service name
spec:
 selector:   # base on this labels it will take req from there
   project: DevOps
   environment: dev
 ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80  # port where u have to send request
     



---

# from this pod we are sending the request
kind: Pod
apiVersion: v1
metadata:
 name: backend
 labels: 
   project: DevOps
   environment: dev
spec:
 containers:
  - name: nginx
    image: nginx

