kind: Deployment
apiVersion: apps/v1
metadata:
 name: nginx
 # labels of deployment resource
 labels:
  app: nginx
  tier: frontend
  purpose: deployment
spec:
 replicaset: 3
 selector:
  matchlabels:
    app: nginx
    tier: frontend
    purpose: deployment
template:
  metadata:
    labels:   
      app: nginx
      tier: frontend
      purpose: deployment
  spec:
    comtainers:
      name: nginx
      image: nginx 
      ports:
      - containerport: 80 
---

kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:  # labels are used as selectors
   app: nginx
   tier: frontend
   purpose: deployment 
ports:
 - protocol: TCP
   port: 80 #  Load balancer related service port
   targetPort: 80
   nodePort: 30007
       
